# Development Stage
FROM node:22-alpine AS dev

WORKDIR /app

COPY backend/package*.json ./
RUN npm install

COPY backend/. ./

CMD ["npx", "nodemon", "server.js"]

# Production Stage
FROM node:22-alpine AS prod

WORKDIR /app

COPY backend/package*.json ./
RUN npm install --omit=dev

COPY backend/. ./

CMD ["node", "server.js"]
