
export const CARD_BG = [
    { id: 1, bgcolor: "linear-gradient(135deg, #e6f8f3  0%, #f7fcfa 100%)" },
    { id: 2, bgcolor: "linear-gradient(135deg, #fef9e7  0%, #fffdf4 100%)" },
    { id: 3, bgcolor: "linear-gradient(135deg, #eaf7ff  0%, #f7fcfa 100%)" },
    { id: 4, bgcolor: "linear-gradient(135deg, #fff2e9  0%, #f7fcfa 100%)" },
    { id: 5, bgcolor: "linear-gradient(135deg, #e7f6fe  0%, #f7fcfa 100%)" },
    { id: 6, bgcolor: "linear-gradient(135deg, #f5f5f5  0%, #f7fcfa 100%)" },
    { id: 7, bgcolor: "linear-gradient(135deg, #fff4fc  0%, #f7fcfa 100%)" },
    { id: 8, bgcolor: "linear-gradient(135deg, #e8fef3  0%, #f7fcfa 100%)" },
    { id: 9, bgcolor: "linear-gradient(135deg, #f03cff  0%, #f7fcfa 100%)" },
    { id: 10, bgcolor: "linear-gradient(135deg, #fef2f2 0%, #f7fcfa 100%)" },
]




export const APP_FEATURES = [
    {
        id: '01',
        title: "Tailored Just for you",
        description: "Get Interview questions ans model answer based on your role, experience and specific focus areeas -no "
    },
    {
        id: "02",
        title: "Learn at Your own Pace",
        description: " Expand answers only when you are read , Dive deeper into any concept istantly with Ai-Poweres detailed expain"
    },
    {
        id: "03",
        title: "Capture your insights",
        description: "Add personal notes to any question and pin import ones to the top-making your learning more organized"
    }, {
        id: "04",
        title: 'Understandthe "why" Behind Answer',
        description: "Beyond jsut answes -unlock detailed concept explanations generated by AI,helping you truly master each other"
    }, {
        id: "05",
        title: "Save,Organize and Revisit",
        description: "Easily save your interview sets,organize them neatly in your dashboard, and pich up your preparation "
    }
]